"""Offline competition packaging and generated DaT inference runtime."""

from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd


SOURCE_FILES = ("dat_preprocessing.py", "model_registry.py")
REQUIRED_BUNDLE_FILES = {
    "main.py", "dat_preprocessing.py", "model_registry.py", "model/weights.pt",
    "model_config.json", "preprocessing.json", "calibration.json",
}


RUNTIME_MAIN = r'''"""Standalone DrivenData DaT inference runtime generated by dat_submission."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from dat_preprocessing import preprocess_nifti
from model_registry import load_model_from_bundle


DATA_ROOT = Path("/code_execution/data")


def apply_saved_calibration(logits: np.ndarray, calibration: dict) -> np.ndarray:
    logits = np.asarray(logits, dtype=np.float64)
    if logits.ndim != 2 or logits.shape[1] != 2:
        raise ValueError("Inference calibration expects logits with shape [N,2].")
    method = str(calibration.get("method", "raw")).lower()
    if method == "temperature":
        temperature = float(calibration.get("temperature", 1.0))
        if not np.isfinite(temperature) or temperature <= 0:
            raise ValueError("Packaged calibration temperature must be finite and positive.")
        logits = logits / temperature
    elif method != "raw":
        raise ValueError(f"Unsupported packaged calibration method '{method}'.")
    shifted = logits - logits.max(axis=1, keepdims=True)
    exp = np.exp(shifted)
    return (exp / exp.sum(axis=1, keepdims=True))[:, 1]


def run_inference(data_root: Path = DATA_ROOT, bundle_root: Path | None = None, output_path: Path | None = None) -> Path:
    bundle_root = Path(bundle_root or Path(__file__).resolve().parent)
    output_path = Path(output_path or Path("/code_execution/submission.csv"))
    data_root = Path(data_root)
    template_path = data_root / "submission_format.csv"
    nifti_dir = data_root / "niftis"
    frame = pd.read_csv(template_path)
    if list(frame.columns) != ["uid", "is_pathologic"]:
        raise ValueError("submission_format.csv must have exactly uid,is_pathologic columns.")
    if frame["uid"].isna().any() or frame["uid"].astype(str).duplicated().any():
        raise ValueError("submission_format.csv contains missing or duplicate UIDs.")
    uids = frame["uid"].astype(str).tolist()
    model_config = json.loads((bundle_root / "model_config.json").read_text(encoding="utf-8"))
    preprocessing = json.loads((bundle_root / "preprocessing.json").read_text(encoding="utf-8"))
    calibration = json.loads((bundle_root / "calibration.json").read_text(encoding="utf-8"))
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = load_model_from_bundle(bundle_root / "model" / "weights.pt", model_config, device=device)
    probabilities = []
    for uid in uids:
        nifti_path = nifti_dir / f"{uid}.nii.gz"
        if not nifti_path.is_file():
            raise FileNotFoundError("A required NIfTI scan is missing from the runtime data directory.")
        tensor = preprocess_nifti(nifti_path, preprocessing)
        with torch.no_grad():
            logits = model(tensor.unsqueeze(0).to(device)).detach().cpu().numpy()
        probability = float(apply_saved_calibration(logits, calibration)[0])
        if not np.isfinite(probability):
            raise RuntimeError("Inference produced a non-finite probability.")
        probabilities.append(float(np.clip(probability, 1e-6, 1.0 - 1e-6)))
    output = frame[["uid", "is_pathologic"]].copy()
    output["is_pathologic"] = probabilities
    values = pd.to_numeric(output["is_pathologic"], errors="coerce").to_numpy(dtype=float)
    if output["uid"].astype(str).tolist() != uids or not np.isfinite(values).all() or np.any((values < 0.0) | (values > 1.0)):
        raise RuntimeError("Inference changed UID order or produced invalid probabilities.")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output.to_csv(output_path, index=False)
    return output_path


if __name__ == "__main__":
    run_inference()
'''


def validate_submission_csv(path: str | Path, template_path: str | Path | None = None) -> dict[str, object]:
    frame = pd.read_csv(path)
    if list(frame.columns) != ["uid", "is_pathologic"]:
        raise ValueError("submission.csv must have exactly uid,is_pathologic columns in that order.")
    if frame["uid"].isna().any() or frame["uid"].astype(str).duplicated().any():
        raise ValueError("submission.csv contains missing or duplicate UIDs.")
    probabilities = pd.to_numeric(frame["is_pathologic"], errors="coerce").to_numpy(dtype=float)
    if not np.isfinite(probabilities).all() or np.any((probabilities < 0.0) | (probabilities > 1.0)):
        raise ValueError("submission.csv probabilities must be finite values in [0, 1].")
    if template_path is not None:
        template = pd.read_csv(template_path)
        if list(template.columns) != ["uid", "is_pathologic"] or frame["uid"].astype(str).tolist() != template["uid"].astype(str).tolist():
            raise ValueError("submission.csv UIDs do not exactly match submission_format.csv order.")
    return {"rows": int(len(frame)), "columns": list(frame.columns), "uids": frame["uid"].astype(str).tolist()}


def validate_submission_zip(path: str | Path) -> dict[str, object]:
    with zipfile.ZipFile(path) as archive:
        if archive.testzip() is not None:
            raise RuntimeError("Generated submission ZIP contains corrupt data.")
        names = set(archive.namelist())
    missing = REQUIRED_BUNDLE_FILES.difference(names)
    if missing:
        raise RuntimeError(f"Generated ZIP is missing required files: {sorted(missing)}")
    if "main.py" not in names:
        raise RuntimeError("Generated submission ZIP must place main.py at its root.")
    return {"file_count": int(len(names)), "required_files": sorted(REQUIRED_BUNDLE_FILES)}


def _read_json_bytes(source: Path, fallback: dict | None = None) -> bytes:
    if source.is_file():
        return source.read_bytes()
    if fallback is None:
        raise FileNotFoundError(str(source))
    return json.dumps(fallback, indent=2, sort_keys=True).encode("utf-8")


def build_submission(model_dir: str | Path, output_zip: str | Path, source_root: str | Path | None = None) -> Path:
    model_dir = Path(model_dir)
    source_root = Path(source_root or Path(__file__).resolve().parent)
    output_zip = Path(output_zip)
    weights = next((model_dir / name for name in ("weights.pt", "final_model.pt", "best_model.pt") if (model_dir / name).is_file()), None)
    missing = [str(source_root / name) for name in SOURCE_FILES if not (source_root / name).is_file()]
    if weights is None:
        missing.append(str(model_dir / "weights.pt or final_model.pt or best_model.pt"))
    for name in ("preprocessing.json", "calibration.json"):
        if not (model_dir / name).is_file():
            missing.append(str(model_dir / name))
    if missing:
        raise FileNotFoundError("Submission bundle inputs are missing: " + ", ".join(missing))
    model_config = _read_json_bytes(model_dir / "model_config.json", {"model": "resnet18_3d", "num_classes": 2, "n_input_channels": 1, "base_channels": 32, "dropout": 0.0})
    preprocessing = _read_json_bytes(model_dir / "preprocessing.json")
    calibration = _read_json_bytes(model_dir / "calibration.json")
    output_zip.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_zip, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        archive.writestr("main.py", RUNTIME_MAIN.encode("utf-8"))
        for name in SOURCE_FILES:
            archive.writestr(name, (source_root / name).read_bytes())
        archive.writestr("model/weights.pt", weights.read_bytes())
        archive.writestr("model_config.json", model_config)
        archive.writestr("preprocessing.json", preprocessing)
        archive.writestr("calibration.json", calibration)
        provenance = model_dir / "provenance.json"
        if provenance.is_file():
            archive.writestr("provenance.json", provenance.read_bytes())
    validate_submission_zip(output_zip)
    return output_zip


build = build_submission


def main() -> None:
    parser = argparse.ArgumentParser(description="Package a final DaT model for the official runtime.")
    parser.add_argument("--model_dir", default="artifacts/dat_parkinsons/final_stage1_unmasked")
    parser.add_argument("--output", default="submission/dat_stage1_unmasked.zip")
    args = parser.parse_args()
    print(json.dumps({"submission_zip": str(build_submission(args.model_dir, args.output))}, indent=2))


if __name__ == "__main__":
    main()
